### ISSUE TITLE
Portal:  Form attributes unable to add list attribute sorting or default values

### ISSUE THREAD

**Issue by mellissatort** [apptreesoftware/revolution#166]
On the user registration page I want to add attribute sorting on the Store list.
http://sandbox.apptreesoftware.com/#/app/service.taylorfreezer.net/beta/builder/device/page/registration
Select Store No attribute.
Under Default Values unable to add new default value.

Under List Options select "Display Options" button
Attribute sorting section indicates no sort attributes selected, but am unable to add sort attributes.
The same issue occurs from the Data Connectors / Lists

App ID:  service.taylorfreezer.net
sandbox / beta

**Comment by sambbaron** [comment]
@mellissatort Fix deployed to portal sandbox `0.8.0-dev.36.10`

**Comment by mellissatort** [comment]
@sambbaron The default values issue is confirmed resolved.  The list options attribute sorting issue is still a problem.  See comments added to #164.
